name: flutter_me
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages


  assets:
    - graphics/body1.png
    - graphics/body2.png
    - graphics/body3.png
    - graphics/body4.png
    - graphics/body5.png
    - graphics/body6.png
    - graphics/body7.png
    - graphics/body8.png
    - graphics/body9.png
    - graphics/body10.png
    - graphics/body11.png
    - graphics/body12.png
    - graphics/head1.png
    - graphics/head2.png
    - graphics/head3.png
    - graphics/head4.png
    - graphics/head5.png
    - graphics/head6.png
    - graphics/head7.png
    - graphics/head8.png
    - graphics/head9.png
    - graphics/head10.png
    - graphics/head11.png
    - graphics/head12.png
    - graphics/legs1.png
    - graphics/legs2.png
    - graphics/legs3.png
    - graphics/legs4.png
    - graphics/legs5.png
    - graphics/legs6.png
    - graphics/legs7.png
    - graphics/legs8.png
    - graphics/legs9.png
    - graphics/legs10.png
    - graphics/legs11.png
    - graphics/legs12.png